apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-service
  name: app-service
  namespace: hyphen
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: hyphen-app
  sessionAffinity: None
  type: ClusterIP