
name: validate-docker

on:
  push:
    branches:
      - master    # Merged PR will trigger a push to the master

jobs:
  docker_push:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: jeewansoori
          password: '${{ secrets.DOCKER_TOKEN }}' 
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: jeewansoori/hyphen-app