
name: ci

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches: [ master ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # -
      #   name: Login to DockerHub
      #   uses: docker/login-action@v1 
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      # -
      #   name: Build and push
      #   id: docker_build
      #   uses: docker/build-push-action@v2
      #   with:
      #     push: true
      #     tags: g1soori/hyphen-app:latest
      # -
      #   name: Image digest
      #   run: echo ${{ steps.docker_build.outputs.digest }}
      - 
        name: Display the path
        run: echo $PATH
        shell: bash
      -
        name: Build the docker image
        run: docker buildx build . --tag jeewan/hyphen --load
      -
        name: Run the app
        run: docker start jeewan/hyphen
      - 
        name: List running image
        run: docker ps
      - 
        name: List docker images
        run: docker image ls
      - 
        name: Test the image
        run: curl localhost