
name: CI

on:
  # push:
#  pull_request_target:
 pull_request:  # This will trigger everytime push

jobs:
  # docker_build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     -
  #       name: Checkout
  #       uses: actions/checkout@v2
  #     -
  #       name: Set up QEMU
  #       uses: docker/setup-qemu-action@v1
  #     -
  #       name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v1
  #     - 
  #       name: Display the path
  #       run: echo $PATH
  #       shell: bash
  #     -
  #       name: Build the docker image
  #       run: docker buildx build . --tag jeewan/hyphen --load
  #     -
  #       name: Run the app
  #       run: docker run -d -p 50000:5000 jeewan/hyphen
  #     - 
  #       name: Sleep 10s
  #       run: sleep 10
  #     - 
  #       name: Test the image
  #       id: curl-result
  #       run: echo "::set-output name=foo::$(curl -sS localhost:50000/api/tasks)"
  #     - 
  #       name: 'Comment PR'
  #       uses: unsplash/comment-on-pr@master
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         foo: ${{ steps.curl-result.outputs.foo }}
  #       with:
  #         msg: '${{ steps.curl-result.outputs.foo }}'

  terraform_plan:
    runs-on: ubuntu-latest
    env:
      RESOURCE_PREFIX: tf
      LOCATION: southeastasia
    #needs: docker_build
    steps:
      - 
        name: terraform setup
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.3
      - 
        name: azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          allow-no-subscriptions: true
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Run TF plan
        id: tf-pan
        run: terraform init
        # run: terraform plan -var resource_prefix=env.RESOURCE_PREFIX -var location=env.LOCATION
        working-directory: k8s
      # - 
      #   name: 'TF Comment PR'
      #   uses: unsplash/comment-on-pr@master
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     foo: ${{ steps.tf-plan.outputs.foo }}
      #   with:
      #     msg: '${{ steps.curl-result.outputs.foo }}'